### ISSUE TITLE
Threading model in Job details pane always shows "not specified"

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/vscode-ide#116]
Using the `threading` annotation on a composite, I expected the threading model to be correctly listed but it is not: 

![image](https://user-images.githubusercontent.com/1179133/86847529-7766f280-c07a-11ea-95ab-a1a2dc2b560f.png)

To reproduce, add the `@threading(model=manual)` annotation to a main composite. Build and run. From the Streams Explorer, select the job. Inspect the reported threading model in the details pane.

**Comment by queeniema** [comment]
We retrieve this `theadingModel` value from the Streams REST API. I checked with the Streams team, and the returned value is the submission configuration value (via `streamtool` or job configuration overlay). The SAM service does not dive into the SPL properties to get this value.

So, you would need to specify the `threadingModel` at submission-time in order to see that value reflected here.

**Comment by queeniema** [comment]
Closing as this is working as designed.
