### ISSUE TITLE
Latest version (1.1.0) doesn't work with Windows

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/vscode-ide#141]
I installed first time VSCode (1.52.1) and the Streams extension (the actual 1.1.0) on a Windows 10 PC with Java 8. 
Installation was OK, no errors. Opening the extension shows me the GUI elements but there is no action behind these elements. No printouts, no action when clicking.
Only going back to Streams extension 1.0.3 brings up the functionality of the Streams extension.

**Comment by queeniema** [comment]
Thank you for reporting this. Version 1.1.0 of the extension now depends on the [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension. That extension requires Java JDK 11 or higher in order to activate. If activation fails, then the IBM Streams extension activation will also fail (which is what you were seeing).

I have updated our extension [documentation](https://ibmstreams.github.io/vscode-ide/docs/quick-start-guide/#installation-and-setup) to include this important step (see step 4).

> Set the `java.home` VS Code setting to a Java JDK version 11 or higher. This satisfies the [requirements](https://ibmstreams.github.io/vscode-ide/docs/developing-java-primitive-operators/#setting-up-vs-code-for-java-development) of the Language Support for Java(TM) by Red Hat extension that this extension depends on.
