### ISSUE TITLE
Rename of streams variable not functioning correctly

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/vscode-ide#23]
When renaming a $xyz variable, the rename appears to go through. On closer inspection, the initial "$" disappears. Also, it might be the case that the instances of the variables might not be changed (this needs to be verified).

Note that the "dialog" for rename shows the text of the variable but not the $, whether or not it was selected before the rename. Renaming of the text part only does not retain the "$". Renaming and also providing the "$" does apparently retain the "$" (not sure about the instances).

Expected behavior alternatives:

1) do not show the "$" but use it behind the scenes in the rename
2) show the rename and allow the user provide the entire variable new name 

For the latter, it is possible (likely?) to accidentally rename without the "$", since the rename dialog default is to have the entire name selected. Question is, would the user notice that they omitted the "$" when overtyping the whole variable name?

**Comment by queeniema** [comment]
This was fixed in the latest [SPL LSP server](https://www.npmjs.com/package/@ibmstreams/spl-lsp) release (0.9.4).

We went with the first alternative mentioned (do not show the "$" but use it behind the scenes in the rename). Note that this only applies to `$` in composite `param` names (`$` symbols in variable names are invalid elsewhere). For instance, in the `Vwap` sample:

```
composite Vwap {
  param 
    expression<set<rstring>> $monitoredTickers : { "IBM", "GOOG", "MSFT" };

  ...
```
