### ISSUE TITLE
We should have a short key for the build-command

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/vscode-ide#79]
We should have a short key for the build-command and for the build-and-submit-command, because these command are very often used during development process.

**Comment by queeniema** [comment]
In VS Code, you can manually assign keyboard shortcuts to those commands. Documentation [here](https://code.visualstudio.com/docs/getstarted/keybindings).

<img width="1513" alt="Screen Shot 2020-06-02 at 8 38 21 AM" src="https://user-images.githubusercontent.com/2454818/83539933-87544b00-a4ac-11ea-811b-7ee6587b76e6.png">

We could have some shortcuts predefined in the extensions. Do you have any suggestions for good shortcut combinations? We do not want the shortcuts to conflict with any of the built-in VS Code shortcuts (e.g., we should not use `cmd+b` for build because that is already used to toggle the side bar visibility).

**Comment by queeniema** [comment]
We've decided to use the following keyboard shortcuts:

OS | *Build* shortcut | *Build and Submit Job* shortcut | Screenshot
---|---|---|---
Windows | `Ctrl+Alt+B` | `Ctrl+Alt+S` | <img width="960" alt="windows" src="https://user-images.githubusercontent.com/2454818/84067553-61331d00-a97c-11ea-8c65-572b2ce4c210.png">
Linux | `Ctrl+Alt+B` | `Ctrl+Alt+S` | <img width="1079" alt="linux" src="https://user-images.githubusercontent.com/2454818/84067663-95a6d900-a97c-11ea-8aa1-f257d8ffb3bd.png">
macOS | `Command+Option+B` | `Command+Option+S` | <img width="909" alt="mac" src="https://user-images.githubusercontent.com/2454818/84067673-9a6b8d00-a97c-11ea-923b-2f317801e9dc.png">

**Comment by joergboe** [comment]
It seems not to work on a RHEL Client.

**Comment by queeniema** [comment]
@joergboe I tried this in a RHEL 8.2 environment and it is working fine for me. Do you see the new keyboard shortcut keys next to build commands in the context menu (i.e.., `Alt+Ctrl+B` / `Alt+Ctrl+S`)?

<img width="1358" alt="Screen Shot 2020-06-19 at 3 10 11 PM" src="https://user-images.githubusercontent.com/2454818/85183044-49427f80-b23f-11ea-8d3d-6f0db269c504.png">
